#pragma once
#include "rust/cxx.h"
#include <memory>
#include <string>
#include <vector>

// Forward declaration is required because main.rs.h references AptClient
// before the class definition is fully parsed.
class AptClient;

// Include the header generated by cxx which contains the PkgInfo definition
#include "legendary/src/main.rs.h"

class AptClient {
public:
    AptClient();
    ~AptClient();

    void init();
    void update_cache();
    rust::Vec<PkgInfo> list_all();
    PkgInfo find_package(rust::String name);
    void mark_install(rust::String name);
    void mark_remove(rust::String name);
    void mark_upgrade();
    bool resolve();

    // Returns download size in bytes
    int64_t get_download_size() const;

    // Simulates the commit for safety in this demo,
    // real implementation requires root and specialized acquire status
    bool commit_changes();

private:
    class Impl;
    std::unique_ptr<Impl> impl;
};

std::unique_ptr<AptClient> new_apt_client();
